// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcFruit.Models;

namespace PcFruit.Migrations
{
    [DbContext(typeof(PcfruitContext))]
    [Migration("20200130134109_new_model")]
    partial class new_model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PcFruit.Models.Measurement", b =>
                {
                    b.Property<long>("MeasurementID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ModuleID");

                    b.Property<long>("SensorID");

                    b.Property<long>("SpecID");

                    b.Property<DateTime>("TimeReceived");

                    b.Property<DateTime>("TimeRegistered");

                    b.Property<double>("Value");

                    b.HasKey("MeasurementID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("SensorID");

                    b.HasIndex("SpecID");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("PcFruit.Models.Module", b =>
                {
                    b.Property<long>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ModuleID");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("PcFruit.Models.Sensor", b =>
                {
                    b.Property<long>("SensorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SensorType");

                    b.HasKey("SensorID");

                    b.ToTable("sensors");
                });

            modelBuilder.Entity("PcFruit.Models.SensorSpec", b =>
                {
                    b.Property<long>("SpecID");

                    b.Property<long>("SensorID");

                    b.Property<long>("SensorSpecID");

                    b.HasKey("SpecID", "SensorID");

                    b.HasIndex("SensorID");

                    b.ToTable("SensorSpec");
                });

            modelBuilder.Entity("PcFruit.Models.Spec", b =>
                {
                    b.Property<long>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Max");

                    b.Property<double>("Min");

                    b.Property<string>("Name");

                    b.HasKey("SpecID");

                    b.ToTable("sensorspecs");
                });

            modelBuilder.Entity("PcFruit.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<long?>("ModuleID");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Salt");

                    b.HasKey("UserID");

                    b.HasIndex("ModuleID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PcFruit.Models.Measurement", b =>
                {
                    b.HasOne("PcFruit.Models.Module", "Module")
                        .WithMany("Measurements")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PcFruit.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PcFruit.Models.Spec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PcFruit.Models.SensorSpec", b =>
                {
                    b.HasOne("PcFruit.Models.Sensor", "Sensor")
                        .WithMany("SensorSpecs")
                        .HasForeignKey("SensorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PcFruit.Models.Spec", "Spec")
                        .WithMany("SensorsSpecs")
                        .HasForeignKey("SpecID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PcFruit.Models.User", b =>
                {
                    b.HasOne("PcFruit.Models.Module", "Module")
                        .WithMany("Users")
                        .HasForeignKey("ModuleID");
                });
#pragma warning restore 612, 618
        }
    }
}
